### PR TITLE
URL Update

### PR DESCRIPTION
**Pull request by MrMonk3y**
www.deepl.com/jsonrpc ist outdated. Use www2.deepl.com/jsonrpc instead.

### CODE REVIEW

**Comment by EmilioK97** [comment]
www2.deepl.com/jsonrpc gives a 403 Forbidden response. Are you sure this is working?

**Comment by MrMonk3y** [comment]
Just tested it again. https://www2.deepl.com/jsonrpc returns: 

{"jsonrpc":"2.0","error":{"code":-32600,"message":"Invalid Request"},"id":null} since I haven't attached any payload. 

https://www.deepl.com/jsonrpc instead gives me a 403 Forbidden response

**Comment by EmilioK97** [comment]
The https protocol was the issue, I'll merge right now.

**Comment by MrMonk3y** [comment]
Cool, thanks! So, I'll give you credits in my Latex translator project.

**Comment by MrMonk3y** [comment]
Hi there! I think you speak German too, so feel free to answer in German if so.

Is there a way to send multiline strings with your script? I’d like to translate complete texts. But with translation = pydeepl.translate(text, "DE", "EN“) I lose the complete structure (tabs, new line etc).

By the way, thanks for offering this wrapper. Makes my life a lot easier :)

Sincerly,

Sascha

**Comment by chriskonnertz** [comment]
> [www.deepl.com/jsonrpc](http://www.deepl.com/jsonrpc) ist outdated. Use www2.deepl.com/jsonrpc instead.

Great hint! Thank you.

**Pull request merged**
